"""Excel export with live formulas.

What you get in the workbook:
  - Cover          : KPI strip + period coverage + cross-statement continuity
  - Summary        : per-statement totals + a Σ row driven by SUMIF formulas
  - Transactions   : flat table across all statements, with a Category column
                     a Statement column, and conditional formatting that
                     highlights low-confidence rows.
  - Categories     : pivot-style breakdown (SUMIF per category against
                     Transactions sheet) -- live, not pre-computed.
  - Anomalies      : every flagged item with severity colour
  - Reconciliation : per-statement deltas; cells turn red on mismatch.

Why formulas (not pre-computed values):
  Finance/ops audiences open the file in Excel and EXPECT to slice it
  themselves. Live SUMIF / SUMIFS formulas let them add a column or filter
  and have totals follow. Pre-baked values lock them out.
"""
from __future__ import annotations
from pathlib import Path
from typing import Iterable

from openpyxl import Workbook
from openpyxl.formatting.rule import CellIsRule, FormulaRule, ColorScaleRule
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

# Colour palette
_HEADER_FILL = PatternFill("solid", fgColor="1F2937")
_HEADER_FONT = Font(color="F9FAFB", bold=True, size=11)
_TITLE_FONT  = Font(bold=True, size=16, color="0F172A")
_OK_FILL     = PatternFill("solid", fgColor="DCFCE7")
_BAD_FILL    = PatternFill("solid", fgColor="FEE2E2")
_WARN_FILL   = PatternFill("solid", fgColor="FEF3C7")
_LOW_CONF_FILL = PatternFill("solid", fgColor="FFF7ED")

_THIN = Side(border_style="thin", color="E5E7EB")
_BORDER = Border(left=_THIN, right=_THIN, top=_THIN, bottom=_THIN)


def _header(ws, row: int, columns: Iterable[str]) -> None:
    for i, col in enumerate(columns, start=1):
        c = ws.cell(row=row, column=i, value=col)
        c.fill = _HEADER_FILL
        c.font = _HEADER_FONT
        c.alignment = Alignment(horizontal="center", vertical="center")
        c.border = _BORDER


def _autosize(ws, max_width: int = 60) -> None:
    for col in ws.columns:
        col_letter = get_column_letter(col[0].column)
        max_len = 0
        for cell in col:
            try:
                if cell.value is not None:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 10), max_width)


def export_workbook(results: list[dict], out_path: str | Path) -> Path:
    """Write a multi-sheet workbook with live formulas. Returns the path."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()

    _write_cover(wb, results)
    _write_summary(wb, results)
    tx_sheet_name = "Transactions"
    tx_row_range = _write_transactions(wb, results, sheet_name=tx_sheet_name)
    _write_categories(wb, results, tx_sheet=tx_sheet_name, tx_range=tx_row_range)
    _write_anomalies(wb, results)
    _write_reconciliation(wb, results)

    wb.save(out_path)
    return out_path


# ---------- Sheets --------------------------------------------------------

def _write_cover(wb: Workbook, results: list[dict]) -> None:
    ws = wb.active
    ws.title = "Cover"
    ws["A1"] = "Bank Statement Extraction Report"
    ws["A1"].font = _TITLE_FONT
    ws.merge_cells("A1:F1")

    ws["A3"] = "Generated by"
    ws["B3"] = "bank-statement-extractor"
    ws["A4"] = "Statements"
    ws["B4"] = len(results)
    ws["A5"] = "Reconciled"
    ws["B5"] = f"={sum(1 for r in results if (r.get('_reconciliation') or {}).get('ok'))}"
    ws["A6"] = "Total transactions"
    ws["B6"] = sum(len(r["transactions"]) for r in results)
    ws["A7"] = "Total anomalies"
    ws["B7"] = sum(len(r.get("_anomalies", [])) for r in results)

    ws["A9"] = "Coverage by statement"
    ws["A9"].font = Font(bold=True, size=13)

    cover_header_row = 11
    _header(ws, cover_header_row, [
        "Period", "Bank", "Account", "Currency",
        "Beginning $", "Ending $", "Deposits #", "Deposits $",
        "Withdrawals #", "Withdrawals $", "Reconciled", "Anomalies",
    ])

    for i, r in enumerate(results, start=cover_header_row + 1):
        a, s = r["account"], r["summary"]
        recon = r.get("_reconciliation") or {}
        ws.cell(i, 1, f"{a['period']['start']} -> {a['period']['end']}")
        ws.cell(i, 2, a.get("bank"))
        ws.cell(i, 3, a.get("account_last4"))
        ws.cell(i, 4, s.get("currency") or "USD")
        ws.cell(i, 5, s["beginning_balance"]).number_format = '$#,##0.00'
        ws.cell(i, 6, s["ending_balance"]).number_format   = '$#,##0.00'
        ws.cell(i, 7, s.get("deposits_count"))
        ws.cell(i, 8, s["deposits_total"]).number_format   = '$#,##0.00'
        ws.cell(i, 9, s.get("withdrawals_count"))
        ws.cell(i, 10, s["withdrawals_total"]).number_format = '$#,##0.00'
        ok = recon.get("ok", False)
        ws.cell(i, 11, "OK" if ok else "MISMATCH").fill = _OK_FILL if ok else _BAD_FILL
        ws.cell(i, 12, len(r.get("_anomalies", [])))

    # Cross-statement continuity formula: each row's beginning should equal
    # the prior row's ending. Add an audit column.
    audit_col = 13
    ws.cell(cover_header_row, audit_col, "Continuity?")
    ws.cell(cover_header_row, audit_col).fill = _HEADER_FILL
    ws.cell(cover_header_row, audit_col).font = _HEADER_FONT
    for i in range(cover_header_row + 2, cover_header_row + 1 + len(results)):
        # =IF(E{i} = F{i-1}, "OK", "DRIFT $"&TEXT(F{i-1}-E{i},"#,##0.00"))
        formula = (
            f'=IF(ROUND(E{i}-F{i-1},2)=0,"OK",'
            f'"DRIFT $"&TEXT(F{i-1}-E{i},"#,##0.00"))'
        )
        ws.cell(i, audit_col, formula)
    _autosize(ws)


def _write_summary(wb: Workbook, results: list[dict]) -> None:
    ws = wb.create_sheet("Summary")
    cols = [
        "#", "Period start", "Period end", "Account",
        "Beginning balance", "Ending balance",
        "Deposits count", "Deposits total",
        "Withdrawals count", "Withdrawals total",
        "Reconciled", "Issues",
    ]
    _header(ws, 1, cols)
    for i, r in enumerate(results, start=2):
        a, s = r["account"], r["summary"]
        recon = r.get("_reconciliation") or {}
        ws.cell(i, 1, i - 1)
        ws.cell(i, 2, a["period"]["start"])
        ws.cell(i, 3, a["period"]["end"])
        ws.cell(i, 4, a.get("account_last4"))
        ws.cell(i, 5, s["beginning_balance"]).number_format = '$#,##0.00'
        ws.cell(i, 6, s["ending_balance"]).number_format   = '$#,##0.00'
        ws.cell(i, 7, s.get("deposits_count"))
        ws.cell(i, 8, s["deposits_total"]).number_format   = '$#,##0.00'
        ws.cell(i, 9, s.get("withdrawals_count"))
        ws.cell(i, 10, s["withdrawals_total"]).number_format = '$#,##0.00'
        ws.cell(i, 11, "OK" if recon.get("ok") else "MISMATCH").fill = (
            _OK_FILL if recon.get("ok") else _BAD_FILL
        )
        ws.cell(i, 12, "; ".join(recon.get("issues", []))[:200])

    # Totals row driven by formulas (so users can filter the sheet and
    # the totals stay dynamic via subtotal-aware formulas).
    last_row = 1 + len(results)
    totals_row = last_row + 1
    ws.cell(totals_row, 1, "TOTAL").font = Font(bold=True)
    ws.cell(totals_row, 7, f"=SUM(G2:G{last_row})")
    ws.cell(totals_row, 8, f"=SUM(H2:H{last_row})").number_format = '$#,##0.00'
    ws.cell(totals_row, 9, f"=SUM(I2:I{last_row})")
    ws.cell(totals_row, 10, f"=SUM(J2:J{last_row})").number_format = '$#,##0.00'
    for c in range(1, 13):
        ws.cell(totals_row, c).fill = PatternFill("solid", fgColor="E0E7FF")
    _autosize(ws)


def _write_transactions(wb: Workbook, results: list[dict], *, sheet_name: str) -> tuple[int, int]:
    """Returns (first_data_row, last_data_row) for cross-sheet references."""
    ws = wb.create_sheet(sheet_name)
    cols = [
        "Statement", "Account", "Date", "Description",
        "Category", "Vendor",
        "Deposit", "Withdrawal", "Amount", "Confidence",
    ]
    _header(ws, 1, cols)
    first_data = 2
    row = first_data
    for r in results:
        period = r["account"]["period"]["start"]
        acct = r["account"].get("account_last4") or ""
        for t in r["transactions"]:
            ws.cell(row, 1, period)
            ws.cell(row, 2, acct)
            ws.cell(row, 3, t["date"])
            ws.cell(row, 4, t["description"])
            ws.cell(row, 5, t.get("category"))
            ws.cell(row, 6, t.get("vendor"))
            ws.cell(row, 7, t.get("deposit")).number_format = '$#,##0.00'
            ws.cell(row, 8, t.get("withdrawal")).number_format = '$#,##0.00'
            # Amount = deposit (positive) or -withdrawal -- so SUMIFs work.
            ws.cell(row, 9,
                    f'=IF(ISNUMBER(G{row}),G{row},-IFERROR(H{row},0))'
                    ).number_format = '$#,##0.00;[Red]-$#,##0.00'
            ws.cell(row, 10, t.get("confidence"))
            row += 1
    last_data = row - 1

    # Conditional formatting: highlight low-confidence rows.
    if last_data >= first_data:
        ws.conditional_formatting.add(
            f"A{first_data}:J{last_data}",
            FormulaRule(
                formula=[f'$J{first_data}<0.5'],
                fill=_LOW_CONF_FILL,
                stopIfTrue=False,
            ),
        )
        # Colour scale on Confidence column.
        ws.conditional_formatting.add(
            f"J{first_data}:J{last_data}",
            ColorScaleRule(
                start_type="num", start_value=0,    start_color="FCA5A5",
                mid_type="num",   mid_value=0.5,    mid_color="FDE68A",
                end_type="num",   end_value=1,      end_color="86EFAC",
            ),
        )
    # Freeze the header.
    ws.freeze_panes = "A2"
    _autosize(ws)
    return first_data, last_data


def _write_categories(wb: Workbook, results: list[dict], *,
                      tx_sheet: str, tx_range: tuple[int, int]) -> None:
    ws = wb.create_sheet("Categories")
    first, last = tx_range
    _header(ws, 1, ["Category", "Count (formula)", "Total amount (formula)"])

    # Collect distinct categories from the data.
    cats: set = set()
    for r in results:
        for t in r["transactions"]:
            if t.get("category"):
                cats.add(t["category"])
    cats_sorted = sorted(cats) or ["(none)"]

    for i, cat in enumerate(cats_sorted, start=2):
        ws.cell(i, 1, cat)
        ws.cell(i, 2,
                f'=COUNTIF({tx_sheet}!E{first}:E{last},A{i})')
        ws.cell(i, 3,
                f'=SUMIF({tx_sheet}!E{first}:E{last},A{i},{tx_sheet}!I{first}:I{last})'
                ).number_format = '$#,##0.00;[Red]-$#,##0.00'
    _autosize(ws)


def _write_anomalies(wb: Workbook, results: list[dict]) -> None:
    ws = wb.create_sheet("Anomalies")
    _header(ws, 1, ["Statement", "Account", "Kind", "Severity", "Tx index", "Message"])
    row = 2
    for r in results:
        period = r["account"]["period"]["start"]
        acct = r["account"].get("account_last4") or ""
        for an in r.get("_anomalies", []):
            ws.cell(row, 1, period)
            ws.cell(row, 2, acct)
            ws.cell(row, 3, an["kind"])
            sev_cell = ws.cell(row, 4, an["severity"])
            sev_cell.fill = {
                "info": _OK_FILL, "warn": _WARN_FILL, "error": _BAD_FILL,
            }.get(an["severity"], _OK_FILL)
            ws.cell(row, 5, an.get("transaction_index"))
            ws.cell(row, 6, an["message"])
            row += 1
    ws.freeze_panes = "A2"
    _autosize(ws)


def _write_reconciliation(wb: Workbook, results: list[dict]) -> None:
    ws = wb.create_sheet("Reconciliation")
    cols = [
        "Period", "Account",
        "Decl deposits $", "Extracted $", "Δ$",
        "Decl deposits #", "Extracted #", "Δ#",
        "Decl withdrawals $", "Extracted $", "Δ$",
        "Decl withdrawals #", "Extracted #", "Δ#",
        "Balance Δ", "Status",
    ]
    _header(ws, 1, cols)
    for i, r in enumerate(results, start=2):
        a, s = r["account"], r["summary"]
        recon = r.get("_reconciliation") or {}
        ws.cell(i, 1, a["period"]["start"])
        ws.cell(i, 2, a.get("account_last4"))
        ws.cell(i, 3, s["deposits_total"]).number_format = '$#,##0.00'
        ws.cell(i, 4, recon.get("deposits_sum")).number_format = '$#,##0.00'
        ws.cell(i, 5, f"=C{i}-D{i}").number_format = '$#,##0.00;[Red]-$#,##0.00'
        ws.cell(i, 6, s.get("deposits_count"))
        ws.cell(i, 7, recon.get("deposits_count_actual"))
        ws.cell(i, 8, f"=F{i}-G{i}")
        ws.cell(i, 9, s["withdrawals_total"]).number_format = '$#,##0.00'
        ws.cell(i, 10, recon.get("withdrawals_sum")).number_format = '$#,##0.00'
        ws.cell(i, 11, f"=I{i}-J{i}").number_format = '$#,##0.00;[Red]-$#,##0.00'
        ws.cell(i, 12, s.get("withdrawals_count"))
        ws.cell(i, 13, recon.get("withdrawals_count_actual"))
        ws.cell(i, 14, f"=L{i}-M{i}")
        ws.cell(i, 15, recon.get("balance_equation_delta")).number_format = '$#,##0.00;[Red]-$#,##0.00'
        ws.cell(i, 16, "OK" if recon.get("ok") else "MISMATCH")

    # Conditional formatting on deltas: red if non-zero.
    last_row = 1 + len(results)
    for col_letter in ("E", "H", "K", "N", "O"):
        ws.conditional_formatting.add(
            f"{col_letter}2:{col_letter}{last_row}",
            CellIsRule(operator="notEqual", formula=["0"], fill=_BAD_FILL),
        )
    ws.conditional_formatting.add(
        f"P2:P{last_row}",
        CellIsRule(operator="equal", formula=['"OK"'], fill=_OK_FILL),
    )
    ws.conditional_formatting.add(
        f"P2:P{last_row}",
        CellIsRule(operator="equal", formula=['"MISMATCH"'], fill=_BAD_FILL),
    )
    _autosize(ws)
