from __future__ import annotations

from typing import Protocol

from dobs.domain.entities.statement import Statement


class StatementCachePort(Protocol):
    async def get(self, key: str) -> Statement | None: ...
    async def put(self, key: str, statement: Statement) -> None: ...
    async def delete(self, key: str) -> bool: ...
    async def clear(self) -> int: ...
    async def keys(self, limit: int = 200) -> list[dict]: ...
    async def stats(self) -> dict: ...
