from __future__ import annotations

from typing import Protocol


class LessonsStorePort(Protocol):
    async def record(self, pattern_hash: str, hint: str, source: str | None = None) -> None: ...
    async def top_hints(self, limit: int = 5) -> list[str]: ...
    async def feedback(self, hint: str, helpful: bool) -> None: ...
    async def stats(self) -> dict[str, object]: ...
